repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^lazy-lock.json$
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.1
    hooks:
      - id: stylua
