repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
    exclude: ^lazy-lock.json$

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.15.1
    hooks:
      - id: stylua
