name: pre-commit

on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1
